"""Simple realistion of tasks and change creating id in User

Revision ID: 844b93743f1e
Revises: 57d906ef5828
Create Date: 2024-11-02 02:34:42.786920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844b93743f1e'
down_revision: Union[str, None] = '57d906ef5828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Users')),
    sa.UniqueConstraint('email', name=op.f('uq__Users__email')),
    sa.UniqueConstraint('id', name=op.f('uq__Users__id'))
    )
    op.create_index(op.f('ix__Users__username'), 'Users', ['username'], unique=True)
    op.create_table('Cdar_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['Users.id'], name=op.f('fk__Cdar_tasks__author_id__Users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Cdar_tasks')),
    sa.UniqueConstraint('id', name=op.f('uq__Cdar_tasks__id'))
    )
    op.create_table('DD_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('dd_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['Users.id'], name=op.f('fk__DD_tasks__author_id__Users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__DD_tasks')),
    sa.UniqueConstraint('id', name=op.f('uq__DD_tasks__id'))
    )
    op.drop_table('tasks')
    op.drop_index('ix__users__username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('premium', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk__users'),
    sa.UniqueConstraint('email', name='uq__users__email'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix__users__username', 'users', ['username'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='fk__tasks__author_id__users'),
    sa.PrimaryKeyConstraint('id', name='pk__tasks')
    )
    op.drop_table('DD_tasks')
    op.drop_table('Cdar_tasks')
    op.drop_index(op.f('ix__Users__username'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
