"""Added account table

Revision ID: ed3bc982d3d0
Revises: 844b93743f1e
Create Date: 2024-11-02 11:59:47.823105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3bc982d3d0'
down_revision: Union[str, None] = '844b93743f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__Cdar_tasks__id'), 'Cdar_tasks', ['id'])
    op.create_unique_constraint(op.f('uq__DD_tasks__id'), 'DD_tasks', ['id'])
    op.create_unique_constraint(op.f('uq__Users__id'), 'Users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__Users__id'), 'Users', type_='unique')
    op.drop_constraint(op.f('uq__DD_tasks__id'), 'DD_tasks', type_='unique')
    op.drop_constraint(op.f('uq__Cdar_tasks__id'), 'Cdar_tasks', type_='unique')
    # ### end Alembic commands ###
