"""Add priority to deadlines

Revision ID: 014674d1c6d6
Revises: 74e0e9ae8076
Create Date: 2025-03-30 19:53:13.220166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '014674d1c6d6'
down_revision: Union[str, None] = '74e0e9ae8076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deadline_tasks', sa.Column('priority', sa.Integer(), nullable=True))
    op.create_index(op.f('ix__Deadline_tasks__author_id'), 'Deadline_tasks', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__Deadline_tasks__author_id'), table_name='Deadline_tasks')
    op.drop_column('Deadline_tasks', 'priority')
    # ### end Alembic commands ###
