"""add schedule

Revision ID: 0f4cdd95a00c
Revises: 573fbd9b4548
Create Date: 2025-01-07 15:19:50.037036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f4cdd95a00c'
down_revision: Union[str, None] = '573fbd9b4548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Deadline_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('deadline_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['Users.id'], name=op.f('fk__Deadline_tasks__author_id__Users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Deadline_tasks')),
    sa.UniqueConstraint('id', name=op.f('uq__Deadline_tasks__id'))
    )
    op.create_table('Schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('week_day', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['Users.id'], name=op.f('fk__Schedule__owner_id__Users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Schedule')),
    sa.UniqueConstraint('id', name=op.f('uq__Schedule__id'))
    )
    op.drop_table('Cdar_tasks')
    op.drop_table('DD_tasks')
    op.drop_column('Users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('DD_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('dd_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['Users.id'], name='fk__DD_tasks__author_id__Users'),
    sa.PrimaryKeyConstraint('id', name='pk__DD_tasks'),
    sa.UniqueConstraint('id', name='uq__DD_tasks__id')
    )
    op.create_table('Cdar_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['Users.id'], name='fk__Cdar_tasks__author_id__Users'),
    sa.PrimaryKeyConstraint('id', name='pk__Cdar_tasks'),
    sa.UniqueConstraint('id', name='uq__Cdar_tasks__id')
    )
    op.drop_table('Schedule')
    op.drop_table('Deadline_tasks')
    # ### end Alembic commands ###
