"""ds

Revision ID: 442a66363360
Revises: 70b79add50cd
Create Date: 2025-03-05 16:05:04.863588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442a66363360'
down_revision: Union[str, None] = '70b79add50cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('text_settings', sa.String(), nullable=True),
    sa.Column('start_working', sa.Time(timezone=True), nullable=True),
    sa.Column('end_working', sa.Time(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Settings')),
    sa.UniqueConstraint('id', name=op.f('uq__Settings__id'))
    )
    op.drop_column('Users', 'text_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('text_settings', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('Settings')
    # ### end Alembic commands ###
