"""Deadline_tasks

Revision ID: 6228d17c94e2
Revises: a92b3f8bb733
Create Date: 2025-01-07 20:58:10.005168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6228d17c94e2'
down_revision: Union[str, None] = 'a92b3f8bb733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deadline_tasks', sa.Column('author', sa.String(), nullable=True))
    op.add_column('Deadline_tasks', sa.Column('status', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq__Deadline_tasks__id'), 'Deadline_tasks', ['id'])
    op.drop_constraint('fk__Deadline_tasks__author_id__Users', 'Deadline_tasks', type_='foreignkey')
    op.create_unique_constraint(op.f('uq__Schedule__id'), 'Schedule', ['id'])
    op.create_unique_constraint(op.f('uq__Users__id'), 'Users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__Users__id'), 'Users', type_='unique')
    op.drop_constraint(op.f('uq__Schedule__id'), 'Schedule', type_='unique')
    op.create_foreign_key('fk__Deadline_tasks__author_id__Users', 'Deadline_tasks', 'Users', ['author_id'], ['id'])
    op.drop_constraint(op.f('uq__Deadline_tasks__id'), 'Deadline_tasks', type_='unique')
    op.drop_column('Deadline_tasks', 'status')
    op.drop_column('Deadline_tasks', 'author')
    # ### end Alembic commands ###
