"""black list add

Revision ID: 6409fea0f9ca
Revises: 442a66363360
Create Date: 2025-03-19 16:27:37.464480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6409fea0f9ca'
down_revision: Union[str, None] = '442a66363360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BlackList',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__BlackList')),
    sa.UniqueConstraint('id', name=op.f('uq__BlackList__id')),
    sa.UniqueConstraint('token', name=op.f('uq__BlackList__token'))
    )
    op.alter_column('Settings', 'start_working',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.Time(),
               existing_nullable=True)
    op.alter_column('Settings', 'end_working',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.Time(),
               existing_nullable=True)
    op.create_index(op.f('ix__Settings__user_id'), 'Settings', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq__Settings__id'), 'Settings', ['id'])
    op.create_foreign_key(op.f('fk__Settings__user_id__Users'), 'Settings', 'Users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__Settings__user_id__Users'), 'Settings', type_='foreignkey')
    op.drop_constraint(op.f('uq__Settings__id'), 'Settings', type_='unique')
    op.drop_index(op.f('ix__Settings__user_id'), table_name='Settings')
    op.alter_column('Settings', 'end_working',
               existing_type=sa.Time(),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=True)
    op.alter_column('Settings', 'start_working',
               existing_type=sa.Time(),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=True)
    op.drop_table('BlackList')
    # ### end Alembic commands ###
