"""new

Revision ID: 70b79add50cd
Revises: b631ff46569e
Create Date: 2025-01-19 15:08:34.277554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b79add50cd'
down_revision: Union[str, None] = 'b631ff46569e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('text_settings', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'text_settings')
    # ### end Alembic commands ###
