"""black_list

Revision ID: 74e0e9ae8076
Revises: 47997bf40df5
Create Date: 2025-03-29 02:19:08.429241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e0e9ae8076'
down_revision: Union[str, None] = '47997bf40df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BlackList',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__BlackList')),
    sa.UniqueConstraint('id', name=op.f('uq__BlackList__id')),
    sa.UniqueConstraint('token', name=op.f('uq__BlackList__token'))
    )
    op.create_unique_constraint(op.f('uq__TaskGroup__id'), 'TaskGroup', ['id'])
    op.create_unique_constraint(op.f('uq__UserToGroup__id'), 'UserToGroup', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__UserToGroup__id'), 'UserToGroup', type_='unique')
    op.drop_constraint(op.f('uq__TaskGroup__id'), 'TaskGroup', type_='unique')
    op.drop_table('BlackList')
    # ### end Alembic commands ###
