"""

Revision ID: 793db269590f
Revises: 74e0e9ae8076
Create Date: 2025-03-31 16:56:56.809771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793db269590f'
down_revision: Union[str, None] = '74e0e9ae8076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_user', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'id_user', name=op.f('pk__Payments')),
    sa.UniqueConstraint('id', name=op.f('uq__Payments__id'))
    )
    op.create_unique_constraint(op.f('uq__BlackList__id'), 'BlackList', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__BlackList__id'), 'BlackList', type_='unique')
    op.drop_table('Payments')
    # ### end Alembic commands ###
