"""Add name to schedule task

Revision ID: 79865c6d8e96
Revises: 6228d17c94e2
Create Date: 2025-01-09 18:57:28.554177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79865c6d8e96'
down_revision: Union[str, None] = '6228d17c94e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Schedule', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix__Schedule__owner_id'), 'Schedule', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__Schedule__owner_id'), table_name='Schedule')
    op.drop_column('Schedule', 'name')
    # ### end Alembic commands ###
