"""make migrations

Revision ID: a92b3f8bb733
Revises: 
Create Date: 2025-01-07 16:59:26.272064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92b3f8bb733'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Users')),
    sa.UniqueConstraint('email', name=op.f('uq__Users__email')),
    sa.UniqueConstraint('id', name=op.f('uq__Users__id'))
    )
    op.create_index(op.f('ix__Users__username'), 'Users', ['username'], unique=True)
    op.create_table('Deadline_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('deadline_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['Users.id'], name=op.f('fk__Deadline_tasks__author_id__Users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Deadline_tasks')),
    sa.UniqueConstraint('id', name=op.f('uq__Deadline_tasks__id'))
    )
    op.create_table('Schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('week_day', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['Users.id'], name=op.f('fk__Schedule__owner_id__Users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__Schedule')),
    sa.UniqueConstraint('id', name=op.f('uq__Schedule__id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Schedule')
    op.drop_table('Deadline_tasks')
    op.drop_index(op.f('ix__Users__username'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
