"""change schedule

Revision ID: b631ff46569e
Revises: 79865c6d8e96
Create Date: 2025-01-12 18:51:16.672670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b631ff46569e'
down_revision: Union[str, None] = '79865c6d8e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Schedule', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('Schedule', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('Schedule', sa.Column('day', sa.Integer(), nullable=True))
    op.add_column('Schedule', sa.Column('start_hours', sa.Integer(), nullable=True))
    op.add_column('Schedule', sa.Column('start_minutes', sa.Integer(), nullable=True))
    op.add_column('Schedule', sa.Column('end_hours', sa.Integer(), nullable=True))
    op.add_column('Schedule', sa.Column('end_minutes', sa.Integer(), nullable=True))
    op.drop_column('Schedule', 'start_time')
    op.drop_column('Schedule', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Schedule', sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('Schedule', sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('Schedule', 'end_minutes')
    op.drop_column('Schedule', 'end_hours')
    op.drop_column('Schedule', 'start_minutes')
    op.drop_column('Schedule', 'start_hours')
    op.drop_column('Schedule', 'day')
    op.drop_column('Schedule', 'month')
    op.drop_column('Schedule', 'year')
    # ### end Alembic commands ###
