"""Added account table

Revision ID: f2f3c375786b
Revises: 2de17401e9bd
Create Date: 2025-01-07 16:14:17.332676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2f3c375786b'
down_revision: Union[str, None] = '2de17401e9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Deadline_tasks', 'deadline_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq__Deadline_tasks__id'), 'Deadline_tasks', ['id'])
    op.create_unique_constraint(op.f('uq__TaskInCalendar_tasks__id'), 'TaskInCalendar_tasks', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__TaskInCalendar_tasks__id'), 'TaskInCalendar_tasks', type_='unique')
    op.drop_constraint(op.f('uq__Deadline_tasks__id'), 'Deadline_tasks', type_='unique')
    op.alter_column('Deadline_tasks', 'deadline_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
